### ISSUE TITLE
Why substracting 1 is needed for contours?

### ISSUE THREAD

**Issue by wangg12** [waspinator/pycococreator#11]
I can not understand why substracting in [this line](https://github.com/waspinator/pycococreator/blob/d29534e36aad6c30d7e4dadd9f4f7b0e344a774c/pycococreatortools/pycococreatortools.py#L48) is needed. @waspinator Could you explain it?

**Comment by waspinator** [comment]
Because `measure.find_contours` will not create closed contours if the mask touches the edges of the image, I first expand the borders by 1 pixel all the way around the image. Then when I run `measure.find_contours`, the contours are displaced by 1 pixel, so I need to subtract them to get their original positions.

**Comment by wangg12** [comment]
OK, thanks @waspinator .
